C: RUN "CALL foo.bar.myProcedure" {}
   PULL_ALL
S: SUCCESS {"fields": ["name", "age"]}
   RECORD ["Alice", 33]
   RECORD ["Bob", 44]
   SUCCESS {}

// these bits are nonsense
FOO
   FOO
//
C: RUN "CALL foo.bar.myProcedure2" {}
   PULL_ALL
S: SUCCESS {"fields": ["name", "age"]}
   RECORD ["Alice", 33]
   RECORD ["Bob", 44]
   SUCCESS {}
C: RUN "X" {}
S: SUCCESS {}



S: this makes no sense on its own
